backend:
  name: github
  repo: taikibonnet/TedouaR-robotic-HUB
  branch: main
  base_url: https://taikibonnet.github.io/TedouaR-robotic-HUB
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "robots"
    label: "Robot Encyclopedia Entries"
    folder: "_robots"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "robot"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["Humanoid", "Industrial", "Service", "Medical", "Educational", "Military", "Research"], required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Video URL", name: "video_url", widget: "string", required: false}
