backend:
  name: github
  repo: taikibonnet/TedouaR-robotic-HUB
  branch: main
  base_url: https://taikibonnet.github.io/TedouaR-robotic-HUB
  auth_endpoint: admin/oauth.html
  open_authoring: true

media_folder: "images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

# Display for the CMS
site_url: https://taikibonnet.github.io/TedouaR-robotic-HUB
display_url: https://taikibonnet.github.io/TedouaR-robotic-HUB
logo_url: https://taikibonnet.github.io/TedouaR-robotic-HUB/images/tedouar-logo.png

# CMS Local Backend - for development only
# local_backend: true

collections:
  - name: "robots"
    label: "Robot Entries"
    folder: "_robots"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "robot"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required: false, allow_multiple: false}
      - {
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["Humanoid", "Industrial", "Service", "Medical", "Educational", "Military", "Research"],
          required: true
        }
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Content", name: "body", widget: "markdown", required: true}
      - {label: "Video URL", name: "video_url", widget: "string", required: false, hint: "YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}
      - {label: "Publication Date", name: "date", widget: "datetime", required: false}
